### ISSUE TITLE
Request: Modify README

### ISSUE THREAD

**Issue by MysteryPoo** [MysteryPoo/SchoolPrototype#7]
I learned how to commit individual line changes within files through the GUI. This will be perfect for managing the project files and other file-dependent commits to reduce conflicts on frequently changed local files.

I'd like to have the README modified to include these instructions ( not verbatim ):
* In the uncommitted changes section, in the list of files yet to be committed, open the 'diff' of the file you wish to commit ( you should see a block of text with red removals and green additions to the file ). Select individual lines you'd like to commit by clicking the line number, or if a block of lines is a valid commit, then click just right of the line number ( it will highlight what will be selected before you click ).

**Comment by appar3ntly** [comment]
README updated to provide instructions for line-by-line commits.
See commit: 8bf48c426e3b4f2e5a823d41b9e219b6c2986959

**Comment by MysteryPoo** [comment]
Thanks!
